version: '3'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: EcomDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
